In [23]:
modelFolder = './'
import os
from numpy import genfromtxt
import numpy as np
import csv
ipath = modelFolder + 'stims'
opath = 'stims_plus400'
input_list = os.listdir(ipath)

In [33]:
def concatenate(pad):
    zeros = np.zeros(pad)
    for stim in input_list:
        if stim.endswith('.csv') == False:
            continue
        stim_fn = ipath + '/' + stim
        print(stim_fn)
        curr_stim = genfromtxt(stim_fn, delimiter=',')
        padded_stim = np.concatenate((curr_stim, zeros), axis=0)
        print(padded_stim)
        with open(opath + '/' + stim, 'w') as f:
            writer = csv.writer(f)
            writer.writerows(map(lambda x: [x], padded_stim))

In [34]:
concatenate(400)

./stims//chirp_mean_-1_freq_0_to_0p1_amp_0_to_1_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_-1_freq_0_to_0p1_amp_0_to_2_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_-1_freq_0_to_0p1_amp_0_to_3_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_-1_freq_0_to_0p1_amp_0_to_4_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_-1_freq_0_to_0p2_amp_0_to_1_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_-1_freq_0_to_0p2_amp_0_to_2_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_-1_freq_0_to_0p2_amp_0_to_3_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_-1_freq_0_to_0p2_amp_0_to_4_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_0_freq_0_to_0p1_amp_0_to_1_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_0_freq_0_to_0p1_amp_0_to_2_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_0_freq_0_to_0p1_amp_0_to_3_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_0_freq_0_to_0p1_amp_0_to_4_lin.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//chirp_mean_0_freq_0_to_0p2_amp_0_to

[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean200_3_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean200_4_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean200_5_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean200_6_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean200_7_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean200_8_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_1_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_2_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_3_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_4_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_5_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_6_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_7_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean25_8_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean50_1_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean50_2_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean50_3_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean50_4_.csv
[0. 0. 0. ... 0. 0. 0.]
./stims//sinsMean50_5_.csv
[0. 0. 0. ... 0. 0. 0.]
.